version: "2.1"
services:
  api:
    build: ./node
    image: nodetodo-api
    ports:
      - 0:8080
    environment:
      - "MONGO_HOST=database"
    links:
      - "mongodb:database"

  mongodb:
    image: mongo:3.2
    ports:
      - 0:27017