version: "2.1"
services:
  api:
    build: ./node
    image: nodetodo-api
    ports:
      - 0:8080
    environment:
      - "MONGO_HOST=database"
    depends_on:
      mongodb:
        condition: service_started
    links:
      - "mongodb:database"

  mongodb:
    image: mongo:3.2
    ports:
      - 0:27017
    healthcheck:
      test: "echo buildInfo | mongo"
      interval: 3s
      timeout: 3s
      retries: 3