---
- hosts: all
  name: install python 2
  gather_facts: no
  sudo: yes
  tasks:
    - name: install python command
      # The python-simplejson module will also install python 2 as a 
      # depeandency
      raw: sudo apt-get -y install python-simplejson 

- hosts: all
  name: set up the hostname and hosts file
  sudo: yes
  vars:
    - my_hostname: nodetodo
  tasks:
    - name: set hostname
      hostname: name="{{ my_hostname }}"
    - name: update /etc/hosts
      template:
        backup: yes
        dest: /etc/hosts
        src: ../templates/hosts
        group: root
        group: root
        mode: 744


- hosts: all
  name: set up a server with nodejs
  gather_facts: no
  sudo: yes
  tasks: 
  - name: fetch the script
    get_url: 
      url: https://deb.nodesource.com/setup_6.x 
      dest: /tmp/setup_6.x
  - name: run the install script
    command: bash /tmp/setup_6.x
  - name: invoke the installer
    apt: 
      name: nodejs
      state: present
  - name: install all dependencies via npm
    command: npm install
    args:
      chdir: /vagrant/node


- hosts: all
  name: set up a server with mongodb
  sudo: yes
  tasks: 
  - name: import the apt key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
  - name: create list file
    file: 
      path: /etc/apt/sources.list.d/mongodb-org-3.2.list
      state: touch
  - name: ensure file exists
    stat:
      path: /etc/apt/sources.list.d/mongodb-org-3.2.list
    register: file_path
  - name: write to list file
    copy:
      content: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" 
      dest: /etc/apt/sources.list.d/mongodb-org-3.2.list
    when: file_path.stat.exists == true
  - name: install mongodb packages
    apt: 
      name: mongodb-org
      state: installed
      update_cache: yes
  - name: add service unit
    copy:
      src: ../templates/mongod.service
      dest: /lib/systemd/system/mongod.service
  - name: start mongod service
    service:
      name: mongod
      state: started

- hosts: all 
...